export const runtime = "edge";

type ClaudeAutomationResponse = {
  action: string;
  parameters?: Record<string, unknown>;
  steps?: string[];
};

const SYSTEM_PROMPT =
  'You are a Photoshop automation agent. When given a retouching instruction, respond ONLY with a JSON object containing: action (the PS action to run), parameters (any settings), and steps (ordered array of what will happen). Keep it machine-readable.';

function extractJsonObject(text: string): ClaudeAutomationResponse {
  // Claude is instructed to return ONLY JSON, but this hardens against accidental whitespace.
  const trimmed = text.trim();
  const start = trimmed.indexOf("{");
  const end = trimmed.lastIndexOf("}");
  if (start === -1 || end === -1 || end <= start) {
    throw new Error("Claude response was not a JSON object.");
  }
  const jsonText = trimmed.slice(start, end + 1);
  const parsed = JSON.parse(jsonText) as ClaudeAutomationResponse;
  if (!parsed || typeof parsed.action !== "string" || !parsed.action.trim()) {
    throw new Error("Claude JSON missing required `action` string.");
  }
  return parsed;
}

function jsxEscapeStringLiteral(s: string) {
  // For embedding into ExtendScript string literals.
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function toExtendScript(instruction: string, plan: ClaudeAutomationResponse) {
  const action = plan.action.trim();
  const params = plan.parameters ?? {};
  const steps = Array.isArray(plan.steps) ? plan.steps : [];

  // This is a "command" string that the next phase can run via ExtendScript.
  // For now we encode the plan as JSON and include a minimal switch for common actions.
  const payload = JSON.stringify(
    { instruction, action, parameters: params, steps },
    null,
    2
  );

  const lines: string[] = [];
  lines.push('/* Generated by /api/execute (Claude) */');
  lines.push(`var __retouchPlan = ${payload};`);
  lines.push("");
  lines.push("function runRetouchPlan(plan) {");
  lines.push("  // TODO (next phase): map actions to real Photoshop DOM / ActionManager code.");
  lines.push('  $.writeln("Retouch action: " + plan.action);');
  lines.push("  switch (plan.action) {");
  lines.push('    case "Frequency Separation":');
  lines.push('    case "Dodge and Burn Setup":');
  lines.push('    case "Background Removal":');
  lines.push('    case "Flatten to Stamp":');
  lines.push("      // Placeholder: implement ActionDescriptor / app.doAction mapping");
  lines.push("      break;");
  lines.push("    default:");
  lines.push("      // Unknown action; still log steps so operator can implement mapping");
  lines.push("      break;");
  lines.push("  }");
  lines.push("  if (plan.steps && plan.steps.length) {");
  lines.push("    for (var i = 0; i < plan.steps.length; i++) {");
  lines.push('      $.writeln("Step " + (i + 1) + ": " + plan.steps[i]);');
  lines.push("    }");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("runRetouchPlan(__retouchPlan);");

  // Some callers may want a single string; join with newlines.
  return lines.join("\n").replace(/\r\n/g, "\n");
}

async function readInstruction(req: Request) {
  const contentType = req.headers.get("content-type") || "";
  if (contentType.includes("application/json")) {
    const json = (await req.json().catch(() => null)) as null | { instruction?: unknown };
    const inst = typeof json?.instruction === "string" ? json.instruction : "";
    return inst.trim();
  }
  const text = await req.text().catch(() => "");
  return text.trim();
}

export async function POST(req: Request) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return new Response("Missing ANTHROPIC_API_KEY.", { status: 500 });

  const instruction = await readInstruction(req);
  if (!instruction) return new Response("Missing instruction.", { status: 400 });

  const upstream = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "anthropic-version": "2023-06-01",
      "x-api-key": apiKey
    },
    body: JSON.stringify({
      model: "claude-sonnet-4-5",
      max_tokens: 500,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: instruction }]
    })
  });

  if (!upstream.ok) {
    const errText = await upstream.text().catch(() => "");
    return new Response(errText || `Anthropic error (${upstream.status})`, { status: 502 });
  }

  const msg = (await upstream.json().catch(() => null)) as any;
  const text = msg?.content?.find?.((c: any) => c?.type === "text")?.text;
  if (typeof text !== "string") {
    return new Response("Unexpected Claude response format.", { status: 502 });
  }

  let plan: ClaudeAutomationResponse;
  try {
    plan = extractJsonObject(text);
  } catch (e: any) {
    return new Response(`Failed to parse Claude JSON: ${e?.message ?? "parse error"}`, {
      status: 502
    });
  }

  const script = toExtendScript(instruction, plan);

  return new Response(script, {
    status: 200,
    headers: {
      "content-type": "text/plain; charset=utf-8",
      "cache-control": "no-store"
    }
  });
}

